### ISSUE TITLE
Loader crashes if there is a syntax error

### ISSUE THREAD

**Issue by molszanski** [webpack/worker-loader#1]
I am not sure if it is a bug or a feature.

But basically, if make a JS syntax error in file loaded via the worker-loader you will see some not-so-helpfull error. 

![a](https://cloud.githubusercontent.com/assets/1117009/5156441/b1e7e326-72c2-11e4-9213-133b14079e05.png)

Other loaders point out a syntax error.

**Comment by revolunet** [comment]
same here :/

**Comment by molszanski** [comment]
My quick midnight advice: fix the syntax with some linter and keep going.

**Comment by revolunet** [comment]
@molszanski thanks but the problem is that when using webpack dev server, it crashes the process

**Comment by molszanski** [comment]
I would guess, that the crash is caused by the wrong JS syntax in one of
your worker files. It should also break normal webpack build and most
browsers.

Try to load your worker module in a regular way and see what is the real
reason.
