### ISSUE TITLE
Name worker chunk files

### ISSUE THREAD

**Issue by dfoverdx** [webpack/worker-loader#5]
I have two different workers.  The only way to distinguish the output files is to include `[hash]` which means my output directory gets flooded with old versions of my worker files.  It would be nice to be able to specify the name, or automatically pull it from the entry filename.

I wrote a quick workaround in index.js:

    // ...
    var workerCompiler = this._compilation.createChildCompiler("worker", outputOptions);
    workerCompiler.apply(new WebWorkerTemplatePlugin(outputOptions));

    // get the specified name from the query, or fall back to the filename without its extension
    var requestName = query.name || request.replace(/^.*[\\\/](.*)(\.[^\.]*)$/, '$1');
    workerCompiler.apply(new SingleEntryPlugin(this.context, "!!" + request, requestName));
    if(this.options && this.options.worker && this.options.worker.plugins) {
    // ...

**Comment by ianwalter** [comment]
:+1: Even if you don't have two workers, how do you specify the naming or replace the old files so that you don't have to keep manually deleting them every time you make a change to the worker file?

**Comment by iMoses** [comment]
Furthermore, I eventually tried using the `inline` configuration to avoid dealing with the file's name, but for some reason, even though the worker *IS* used as an inline string, a file is still being created for the worker.

**Comment by sokra** [comment]
> even though the worker IS used as an inline string, a file is still being created for the worker.

Not all browser support passing worker code inline to the Worker so a file is emitted in every case as fallback.

**Comment by brunovandamme** [comment]
This is fixed with https://github.com/webpack/worker-loader/commit/b19200bcf3946db1d6de87ed41c1f5df1382cd7a. It is now possible to specify the name in the loader query.
