### ISSUE TITLE
Uncaught SecurityError: Failed to construct 'Worker': Script

### ISSUE THREAD

**Issue by bvaughn** [webpack/worker-loader#8]
Apologies if I'm misunderstanding something obvious, but I'm unable to load a worker script with this loader. The error I'm getting is...

```
Uncaught SecurityError: Failed to construct 'Worker': Script at 'http://localhost:9010/console-assets/6edae5507e4e62f5e077.worker.js' cannot be accessed from origin 'http://localhost:3000'.
  module.exports @SearchIndex.js:2
  Search @Search.js:32
  ...
```

My code is basically the same as what's in the README:
```javascript
import Worker from 'worker!./SearchIndex'

const worker = new Worker()
```

My local application is running on port 3000 via `webpack-dev-server`. Any advice?

**Comment by bvaughn** [comment]
Was able to get this working by changing my import to

```javascript
import Worker from 'worker?inline=true!./SearchIndex'
```

**Comment by Neutrino-Sunset** [comment]
The webpack documentation still suggests the approach that doesn't work.

https://webpack.js.org/loaders/worker-loader/

Could someone update it please?
